### ISSUE TITLE
Air-gapped key import via QR not working on iOS

### ISSUE THREAD

**Issue by haromz** [nunchuk-io/nunchuk-mobile-issues#12]
On iOS I'm unable to import any air-gapped key via QR code. I tried couple of different wallets from Sparrow (xpub, zpub) and Specter wallet config file via QR, etc.
When I scan the QR I receive a `std::exception` error. I attached a screenshot with this.
I'm using iOS 15.6 on an iPhone 12 Pro.
![IMG_0919](https://user-images.githubusercontent.com/14028407/181841508-aa4d8c6e-f4ee-4d10-936a-ef7919b56771.jpg)

**Comment by haromz** [comment]
I guess this happens only for me, as nobody is bothering to respond to this issue.

**Comment by nogibi** [comment]
Sorry to hear that @haromz,
Our wallet currently does not support import xpub/zpub direct via QR, we'll take a look at the Specter QR format.
In the meantime, can you try exporting wallet as Output Descriptor file in Sparrow and then in Nunchuk use `Add wallet (plus + icon)` -> `Recover existing wallet` -> `Recover using BSMS/descriptors` -> choose the file.

**Comment by haromz** [comment]
Thank you, I will try that method. But then why is a scan QR code button on the add key screen if it is not supported? It is a bit confusing.

**Comment by nogibi** [comment]
in Nunchuk you can scan QR to import key or scan QR to import wallet (these are 2 different features), the `Add air-gapped key` (import key) via QR currently supports Electrum format, Generic JSON, Keystone, Passport format but unfortunately not raw xpub, We need more information like master fingerprint, derivation path, etc.

Please let me know if import wallet via Output Descriptor file works, thank you.

**Comment by haromz** [comment]
Thank you for the detailed explanation. I tried with the output descriptor and it's working. Keep up the good work, I really like your product 😀

**Comment by BeardMatt** [comment]
Just got stuck on this for hours until I ran across this. Any chance to support Trezor QR code here? I can't figure out how to import my trezor into nunchuk. I used trezorctl to output the descriptor but couldn't figure out what nunchuk was looking for. Does anyone have trezor and managed to get nunchuck to be used as a watch only wallet?
