### ISSUE TITLE
Compatibility with electrs

### ISSUE THREAD

**Issue by sanyangGitHub** [nunchuk-io/nunchuk-mobile-issues#13]
Hi
Amazing job guys !
Is the mobile app compatible with electrs as electrum server connection ? Can't connect to my node running electrs

**Comment by hugohn** [comment]
Thanks @sanyangGitHub ! Since electrs and ElectrumX use the same API, in theory they should be compatible with one another. But we haven't tested this setup out specifically.

**Comment by mariodian** [comment]
I also can't connect to my electrs server (iOS, MacOS). The server is working because Sparrow and Blue has no issues connecting to it.

**Comment by hugohn** [comment]
@mariodian @sanyangGitHub  try prefixing the address with ssl://

**Comment by sanyangGitHub** [comment]
Yeah, it works !!

**Comment by iWarpBTC** [comment]
> @mariodian @sanyangGitHub  try prefixing the address with ssl:// 

This hint maybe should be in the app!

**Comment by cmyk** [comment]
I have the exact same issue. I can connect using sparrow, locally and remotely no problem to my electrs server. But with nunchuk on iOS I cannot. I used the ssl:// format. Does the port matter? I use 7004
Update: figured it out. You guys don't include a proxy. You have to run your own proxy on the client.
Really, this is not very user friendly.
