### ISSUE TITLE
Apk for older android versions. 

### ISSUE THREAD

**Issue by Transisto** [nunchuk-io/nunchuk-mobile-issues#15]
I was trying to use Nunchuck on a cheaper relatively recent phone buy play store isn't letting me install it.

I think given the multi device nature of multisigs setup the wallet could work with some OS level security risks.

Maybe a different apk could allow every features but single sig software wallets and run on old Android OS.

**Comment by Transisto** [comment]
This is worst than I thought, Looks like only 25% of phones can currently run Nunchuck
If Android 11 is too old..
https://gs.statcounter.com/os-version-market-share/android

**Comment by haiithust** [comment]
![image](https://user-images.githubusercontent.com/22370114/197653972-9823000b-8012-452f-9e43-ec4f2b94e20b.png)
The application supports from API level 21 (Android 5.0)

**Comment by Transisto** [comment]
It's a Samsung https://www.phonemore.com/specs/samsung/galaxy-a03-core/sm-a032mds/

App doesn't show in play store and  get a red "Your device isn't compatible with this version." when go direct to the app link.

Could it be because it doesn't have a fingerprint reader?
The resolution? 
SC9863A CPU

**Comment by haiithust** [comment]
it's not related to android version, maybe due to the architecture of the processor. our application only support arm64-v8a processor

**Comment by Transisto** [comment]
Makes sense, thank you.
