### ISSUE TITLE
Deleting NFC key does not work on iOS

### ISSUE THREAD

**Issue by haromz** [nunchuk-io/nunchuk-mobile-issues#22]
When trying to delete a Coldcard NFC key on iOS, it does not remove the key from the app. 

**Prerequisite:** 
Coldcard NFC key is listed in the keys list.
No wallet is associated with the NFC key.

**Steps to reproduce:**

1. Tap Coldcard NFC key
2. Tap "..." on the upper right corner on the key page
3. Tap "Remove key"
4. Tap "Yes" on the confirmation dialog

Back on the main (wallets) screen, the key is still present in the app, listed in the keys list.

**Tested on:**
iPhone 12 pro
iOS v16.1.1
Nunchuk v1.9.17 in guest mode (not signed in)

**Comment by haromz** [comment]
Anybody can confirm if it's working or not for them?

**Comment by nogibi** [comment]
Hello @haromz ,
Could you try deleting the key with latest Nunchuk app (version 1.9.18)

**Comment by haromz** [comment]
I just tried, still doesn't work. I tried multiple times, restarted wallet etc. It does not delete it in any scenario.

**Comment by nogibi** [comment]
The issue should be resolved with our latest version on the App Store (1.9.19). Please try it and let us know if it works. Thank you for reporting the issue. @haromz

**Comment by haromz** [comment]
I checked now and I can confirm the fix. Thanks a lot! Keep up the good work, the app is awesome!
