### ISSUE TITLE
iOS 1.9.52 crashes upon start

### ISSUE THREAD

**Issue by tschweg** [nunchuk-io/nunchuk-mobile-issues#30]
Hi, 
after upgrading to 1.9.52, the iOS app won't start properly. The logo screen is shown for a couple of seconds and then the app crashes.

**Comment by hugohn** [comment]
Thanks for reporting @tschweg . We’ve confirmed the issue and have submitted a fix to the App Store. The new version will be available as soon as Apple completes the review.

**Comment by hugohn** [comment]
@tschweg it’s available now. Can you try updating the app?

**Comment by tschweg** [comment]
Looks good. 1.9.53 seems to work and the app opens as expected.

**Comment by hugohn** [comment]
Great! Thanks for checking! @tschweg
