### ISSUE TITLE
No Tor connection to my node 

### ISSUE THREAD

**Issue by Alex71btc** [nunchuk-io/nunchuk-mobile-issues#7]
It's not possible to get access to electrum server via Tor in android app.
Please as that important feature, since I would like to connect to my umbrel node,  there is only tor access possible.

**Comment by Alex71btc** [comment]
I was now able to connect to node via tailscale vpn!

**Comment by acurious** [comment]
Any guide somewhere how to do it?

**Comment by acurious** [comment]
Seems like I was able to connect with Orbot in VPN mode when I added ssl:// in front of my onion address under Nunchuk's Network settings. Took a looong time to sync though.
